<table class="table table-bordered">
	<thead>
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th>Apellido Paterno</th>
			<th>Apellido Materno</th>
			<th>Opciones</th>
		</tr>
	</thead>
	
	<?php foreach($this->lista as $usuario): ?>
	<tr> 
	    <td><?php echo $this->escapehtml($usuario['id']); ?></td>
		<td><?php echo $this->escapehtml($usuario['nombre']); ?></td>
		<td><?php echo $this->escapehtml($usuario['primer_apellido']); ?></td>
		<td><?php echo $this->escapehtml($usuario['segundo_apellido']); ?></td>
	<td>
		<a class="btn btn-success" href="/usuario/actualizar/<?php echo $usuario['id'];?>">Editar</a>
    	<a class="btn btn-danger"  href="/usuario/eliminar/<?php echo $usuario['id'];?>">Borrar</a>
	</td>
	</tr>
	<?php endforeach; ?>
	
	

  
  
 
  
  
</table>

<a href="/usuario/agregar" class="btn btn-primary">Nuevo Usuario </a>

 



